package com.boleteria.enums;

public enum TipoMensaje {
    RECARGA, ESPERA, ACTUALIZAR, GUARDAR, ELIMINAR, LISTA_VACIA, CIUDAD_DESTINO, FECHA_MINMAX, FECHA_REGRESO, EMPTY_BUS,
    MAX_ASIENTO, ENABLE_AUTO, SELECCIONAR_ASIENTOS, MAX_PASAJEROS, EMPTY_BUSREGRESO, MENOR_EDAD, ERROR_CELULAR,
    ERROR_DIRECCION, EXISTE_ADULTO, SIN_BUSSIDA, ACEPTAR_TP
}